# fly.toml app configuration file generated for durumari-net on 2025-05-07T21:52:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'durumari-net'
primary_region = 'nrt'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
